swagger: '2.0'
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    description: ''
    type: apiKey
  security:
    - Bearer: []
basePath: /shipment
host: 0.0.0.0
schemes:
  - http
info:
  title: shipment-service
  version: '1.0'
  description: This API helps in getting the shipment.
  contact:
    name: abcd
    url: 'http://api.abcd.com'
    email: api@abcd.com
  license:
    name: Proprietary
    url: 'http://license.abcd.com'
paths:
  /op/v1/order/shipment/create:
    post:
      tags:
        - shipment
      summary: createShipment
      operationId: createShipment
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: shipmentRequest
          description: shipmentRequest
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
  '/op/v1/order/shipments/ponumber/{ ponumber} ':
    get:
      tags:
        - shipment
      summary: getAllShipmentByPONumber
      operationId: getAllShipmentByPONumber
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: ponumber
          in: path
          description: poNumber
          required: true
          type: string
        - name: filter
          in: query
          description: filter
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
  '/op/v1/order/shipments/shipmentref/{ shipmentref} ':
    get:
      tags:
        - shipment
      summary: getShipmentByShipmentRef
      operationId: getShipmentByShipmentRef
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: shipmentref
          in: path
          description: shipmentRef
          required: true
          type: string
        - name: filter
          in: query
          description: filter
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
  '/op/v1/order/shipments/{ shipmentorderid} ':
    get:
      tags:
        - shipment
      summary: getAllShipmentByOrderId
      operationId: getAllShipmentByOrderId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: shipmentorderid
          in: path
          description: shipmentOrderId
          required: true
          type: string
        - name: filter
          in: query
          description: filter
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
  /op/v1/order/shipment/update:
    put:
      tags:
        - shipment
      summary: updateShipment
      operationId: updateShipment
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: shipmentRequest
          description: shipmentRequest
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
  '/op/v1/order/shipment/{ shipmentorderid} /{ shipmentid} ':
    get:
      tags:
        - shipment
      summary: getShipmentByShipmentId
      operationId: getShipmentByShipmentId
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: shipmentid
          in: path
          description: shipmentId
          required: true
          type: integer
          format: int32
        - name: shipmentorderid
          in: path
          description: shipmentOrderId
          required: true
          type: string
        - name: filter
          in: query
          description: filter
          required: false
          type: boolean
          default: true
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Order'
definitions:
  Order:
    description: ''
    type: object
    properties: {}
    x-model-class: com.abcd.uop.model.Order
