swagger: '2.0'
info:
  description: api.description
  version: '1.0'
  title: schedule-service
  termsOfService: api.termsOfService
  contact:
    name: api.contact.name
    url: 'http://api.contact.url'
    email: api@demo.com
  license:
    name: api.license.name
    url: 'http://api.license.url'
host: '0.0.0.0:12080'
basePath: /schedule-service/1.0
schemes:
  - http
paths:
  /schedules:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: hostScheduledDate
          in: query
          description: host scheduled date which by default is current date
          required: false
          type: string
      responses:
        '200':
          description: success
          schema:
            type: array
            items:
              $ref: '#/definitions/Schedule'
      x-camelContextId: schedule-service
      x-routeId: GET /schedules
  '/schedules/{scheduleId}':
    get:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: scheduleId
          in: path
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Schedule'
      x-camelContextId: schedule-service
      x-routeId: 'GET /schedules/{scheduleId}'
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: scheduleId
          in: path
          description: ''
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: ''
          required: true
          schema:
            $ref: '#/definitions/Schedule'
      responses:
        '204':
          description: success
      x-camelContextId: schedule-service
      x-routeId: 'PUT /schedules/{scheduleId}'
    delete:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: scheduleId
          in: path
          description: ''
          required: true
          type: integer
          format: int64
      responses:
        '204':
          description: success
      x-camelContextId: schedule-service
      x-routeId: 'DELETE /schedules/{scheduleId}'
definitions:
  Schedule:
    type: object
    properties:
      id:
        type: integer
        format: int64
      externalIdentifier:
        type: string
      aircraftId:
        type: integer
        format: int32
      airlineId:
        type: integer
        format: int32
      route:
        type: string
      hostScheduledDate:
        type: string
      hostUTCOffset:
        type: integer
        format: int32
      flightType:
        type: string
      statusCode:
        type: string
      statusTime:
        type: string
      statusMessage:
        type: string
      gateNumber:
        type: string
      flightNumber:
        type: integer
        format: int32
      category:
        type: string
      numberOfStops:
        type: integer
        format: int32
      originTerminal:
        type: string
      destinationTerminal:
        type: string
      originAirportId:
        type: integer
        format: int32
      destinationAirportId:
        type: integer
        format: int32
      stopOverId:
        type: array
        items:
          type: integer
          format: int32
      durationInMinutes:
        type: integer
        format: int32
      otherScheduledDate:
        type: string
      otherUTCOffset:
        type: integer
        format: int32
      statusUpdateDateTime:
        type: string
    x-className:
      type: string
      format: demo.cosmos.core.schedule.model.Schedule
