package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * LineQuantityStatus generated by hbm2java
 */
@Entity
@Table(name = "LineQuantityStatus")
@Getter
@Setter
@NoArgsConstructor
public class LineQuantityStatus implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private long id;

    @Column(name = "Order_Pk")
    private String orderPk;

    @Column(name = "Order_Id")
    private String orderId;

    @Column(name = "Line_Id")
    private Long lineId;

    @Column(name = "Fulfilment_Location")
    private String fulfilmentLocation;

    @Column(name = "Fulfilment_Divison")
    private String fulfilmentDivison;

    @Column(name = "Fulfilment_Store")
    private String fulfilmentStore;

    @Column(name = "Status_Quantity")
    private String statusQuantity;

    @Column(name = "Status")
    private String status;
}
