package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import java.io.Serializable;
import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * LockStatsTopMinuteId generated by hbm2java
 */
@Getter
@Setter
@NoArgsConstructor
public class LockStatsTopMinuteId implements java.io.Serializable {

    @Column(name = "INTERVAL_END", length = 35)
    private Date intervalEnd;

    @Column(name = "ROW_RANGE_START_KEY")
    private byte[] rowRangeStartKey;

    @Column(name = "LOCK_WAIT_SECONDS", precision = 15, scale = 16)
    private Double lockWaitSeconds;

    @Column(name = "SAMPLE_LOCK_REQUESTS")
    private Serializable sampleLockRequests;
}
