package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * MessageStore generated by hbm2java
 */
@Entity
@Table(name = "MessageStore")
@Getter
@Setter
@NoArgsConstructor
public class MessageStore implements java.io.Serializable {

    @Id
    @Column(name = "MessageId", unique = true, nullable = false)
    private String messageId;

    @Column(name = "Message")
    private String message;
}
