package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * OrderLineTax generated by hbm2java
 */
@Entity
@Table(name = "OrderLineTax")
@Getter
@Setter
@NoArgsConstructor
public class OrderLineTax implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private long id;

    @Column(name = "Order_Pk")
    private String orderPk;

    @Column(name = "Order_Id")
    private String orderId;

    @Column(name = "Line_Id")
    private Long lineId;

    @Column(name = "Tax_Type")
    private String taxType;

    @Column(name = "Tax_Value")
    private String taxValue;

    @Column(name = "Tax_Fee")
    private String taxFee;

    @Column(name = "Tax_Date")
    private String taxDate;
}
