package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * OrderLine generated by hbm2java
 */
@Entity
@Table(name = "OrderLine")
@Getter
@Setter
@NoArgsConstructor
public class OrderLine implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private long id;

    @Column(name = "Order_Pk")
    private String orderPk;

    @Column(name = "Order_Id")
    private String orderId;

    @Column(name = "Line_Id")
    private Long lineId;

    @Column(name = "Upc_Number")
    private Long upcNumber;

    @Column(name = "Ordered_Qty")
    private Long orderedQty;

    @Column(name = "Delivery_Type")
    private String deliveryType;

    @Column(name = "Line_Total")
    private Long lineTotal;

    @Column(name = "Fulfillment_Type")
    private String fulfillmentType;

    @Column(name = "Product_Type")
    private String productType;
}
