package demo.order.v1.core.shipment.v6.dao.entity;

// Generated 11 Feb, 2021 4:00:55 PM by Hibernate Tools 5.4.21.Final
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

/**
 * OrderMaster generated by hbm2java
 */
@Entity
@Table(name = "OrderMaster")
@Getter
@Setter
@NoArgsConstructor
public class OrderMaster implements java.io.Serializable {

    @Id
    @Column(name = "id", unique = true, nullable = false)
    private long id;

    @Column(name = "Order_Pk")
    private String orderPk;

    @Column(name = "Order_Id")
    private String orderId;

    @Column(name = "Order_Type")
    private String orderType;

    @Column(name = "Reservation_Nbr")
    private String reservationNbr;

    @Column(name = "Seller_Order_Id")
    private String sellerOrderId;

    @Column(name = "Order_Status")
    private String orderStatus;

    @Column(name = "Service_Name")
    private String serviceName;

    @Column(name = "Created_By")
    private String createdBy;

    @Column(name = "Source_Channel")
    private String sourceChannel;
}
